name: matrix_debug_page
description: A simple page with matrix effect(code rain) show user device info or custom debug information
version: 1.0.0
homepage: https://github.com/rtugeek/matrix_debug_page

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.4
  clipboard: ^0.1.3
  flutter_screenutil: ^5.5.3+2
  package_info_plus: ^1.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
